base_url: "http://radiantcapsule.com"
author_name: "Alex Vollmer"
author_email: "alex@radiantcapsule.com"
output_dir: output
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_unified
